# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ modulesPath, pkgs, ... }:

{
  imports = [
    # Include the default incus configuration.
    "${modulesPath}/virtualisation/incus-virtual-machine.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
    ./grafana.nix
    ./prometheus.nix
    ./census-exporter.nix
  ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-enp5s0" = {
      matchConfig.Name = "enp5s0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
        IPv6PrivacyExtensions = false;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  security.acme.defaults.email = "noc@frn.de";
  security.acme.acceptTerms = true;

  networking.nftables.enable = true;

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  environment.systemPackages = with pkgs; [
    vim
    nano
    wget
    curl
    iperf3
    git
    htop
    tmux
    mtr
    parted
    ncdu
    tcpdump
    whois
    netcat
    jq
    tree
    upterm

    dig
    inetutils

    unzip
    zip
  ];

  time.timeZone = "Europe/Berlin";

  services.openssh = {
    enable = true;
    settings.PasswordAuthentication = false;
  };

  users.users.root.openssh.authorizedKeys.keys = [
   "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKdnwVGpMaBv5Bx2XuIvuBI+b4HNaPYcuPoGSzZi/Z5R ffrn@tom v1"
  ];

  system.stateVersion = "25.11"; # Did you read the comment?
}
